FROM ubuntu:jammy

ENV TERM=linux

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
    && apt-get install -y --no-install-recommends gnupg software-properties-common \
    && add-apt-repository ppa:ondrej/php \
    && apt-get update \
    && apt-get -y --no-install-recommends install \
        ca-certificates \
        curl \
        unzip \
        git \ 
        wget \
        nano \
        vim \
        zsh \
        #cron \
        php8.3-apcu \
        php8.3-cli \
        php8.3-curl \
        php8.3-mbstring \
        php8.3-opcache \
        php8.3-readline \
        php8.3-xml \
        php8.3-zip \
        php8.3-gd \
        php8.3-bcmath \ 
        php8.3-igbinary \ 
        php8.3-imagick \ 
        php8.3-intl \ 
        php8.3-mysql \ 
        php8.3-redis \ 
        php8.3-soap \ 
        php8.3-sqlite3 \ 
        php8.3-fpm \
        php-excimer \
    && apt-get clean

# Backup the original file
RUN cp /etc/adduser.conf /etc/adduser.conf.bak

# Change the value of DSHELL to /bin/zsh
RUN sed -i 's/^DSHELL=.*/DSHELL=\/bin\/zsh/' /etc/adduser.conf

RUN wget https://get.symfony.com/cli/installer -O - | bash
COPY --from=composer:2 /usr/bin/composer /usr/bin/composer
RUN composer self-update

RUN rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* /usr/share/doc/* ~/.composer

COPY overrides.conf /etc/php/8.3/fpm/pool.d/z-overrides.conf

#RUN wget http://pear.php.net/go-pear.phar; php go-pear.phar

RUN composer global config --no-plugins allow-plugins.dg/composer-frontline true
RUN composer global require dg/composer-frontline

STOPSIGNAL SIGQUIT

EXPOSE 9000

CMD ["/usr/sbin/php-fpm8.3", "-O" ]
