FROM ubuntu:jammy

ENV TERM=linux

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
    && apt-get install -y --no-install-recommends gnupg software-properties-common \
    && add-apt-repository ppa:ondrej/php \
    && apt-get update \
    && apt-get -y --no-install-recommends install \
        ca-certificates \
        curl \
        unzip \
        git \
        wget \
        nano \
        vim \
        zsh \
        #cron \
        php8.4-apcu \
        php8.4-cli \
        php8.4-curl \
        php8.4-mbstring \
        php8.4-opcache \
        php8.4-readline \
        php8.4-xml \
        php8.4-zip \
        php8.4-gd \
        php8.4-bcmath \
        php8.4-igbinary \
        php8.4-imagick \
        php8.4-intl \
        php8.4-mysql \
        php8.4-redis \
        php8.4-soap \
        php8.4-sqlite3 \
        php8.4-fpm \
        php-excimer \
    && apt-get clean

# Backup the original file
RUN cp /etc/adduser.conf /etc/adduser.conf.bak

# Change the value of DSHELL to /bin/zsh
RUN sed -i 's/^DSHELL=.*/DSHELL=\/bin\/zsh/' /etc/adduser.conf

RUN wget https://get.symfony.com/cli/installer -O - | bash
COPY --from=composer:2 /usr/bin/composer /usr/bin/composer
RUN composer self-update

RUN rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* /usr/share/doc/* ~/.composer

COPY overrides.conf /etc/php/8.4/fpm/pool.d/z-overrides.conf

#RUN wget http://pear.php.net/go-pear.phar; php go-pear.phar

RUN composer global config --no-plugins allow-plugins.dg/composer-frontline true
RUN composer global require dg/composer-frontline

STOPSIGNAL SIGQUIT

EXPOSE 9000

CMD ["/usr/sbin/php-fpm8.4", "-O" ]
