name: build

on:
  pull_request:
  push:
    branches: [main]

  # Allow workflow to be manually run from the GitHub UI
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - 
        name: Checkout
        uses: actions/checkout@v3

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - 
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - 
        name: Build & Push Dev
        uses: docker/build-push-action@v3
        with:
          push: true
          context: .
          file: Dockerfile.dev
          platforms: linux/amd64,linux/arm64
          tags: eyeballapp/php-dev:8.2,eyeballapp/php-dev:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - 
        name: Build & Push Prod
        uses: docker/build-push-action@v3
        with:
          push: true
          context: .
          file: Dockerfile.prod
          platforms: linux/amd64,linux/arm64
          tags: eyeballapp/php:8.2,eyeballapp/php:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max